version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    ports:
      - ${PORT}:27017
    restart: unless-stopped

volumes:
  mongodb:
